spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog

server:
    port: 8082
    
jpa:  
     defer-datasource-initialization: true
     hibernate:
       ddlAuto: create-drop

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true    
      
