server:
  port: 8080
  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      Instance:
        preferIpAddress: true
       
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movies-service-route
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
