spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender: 
      type: rabbit
    enable: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/movies
  jpa:  
     defer-datasource-initialization: true
     hibernate:
       ddlAuto: create-drop

server:
    port: 8081

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
    instances:
        movies:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
