spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/series

server:
  port: 8083

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      resilience4j.circuitbreaker:
    instances:
        movies:
          allowHealthIndicatorToFail: false
          registerHealthIndicator: true
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowType: TIME_BASED
          minimumNumberOfCalls: 4
          waitDurationInOpenState: 5s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10
